[ req ]
default_bits       = 2048
distinguished_name = req_DN
string_mask        = nombstr

[ req_DN ]
commonName                      = "6. Common Name              (eg, username)  "
commonName_max                  = 64
commonName_default              = GLOBAL\\GlobalAdmin
