name: Docker Image CI nzyme challenge

on:
  push:
    branches:
      - 'challenge'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v3   

      - name: Set lowercase repository name
        id: set_lowercase_repo
        run: |
          LOWERCASE_REPO=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=lowercase_repo::${LOWERCASE_REPO}"

      # Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.set_lowercase_repo.outputs.lowercase_repo }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Push
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./Clients
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.set_lowercase_repo.outputs.lowercase_repo }}-clients:challenge
            ghcr.io/${{ steps.set_lowercase_repo.outputs.lowercase_repo }}-clients:challenge
          labels: ${{ steps.meta.outputs.labels }}